"""table foreign keys

Revision ID: 1578c1379d7b
Revises: 82e2b5d48000
Create Date: 2025-03-17 13:04:20.109895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1578c1379d7b'
down_revision: Union[str, None] = '82e2b5d48000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Actions', 'Rule', ['RuleID'], ['RuleID'])
    op.create_foreign_key(None, 'Actions', 'Conditions', ['CID'], ['CID'])
    op.create_foreign_key(None, 'Conditions', 'Selectors', ['LeftSID'], ['SID'])
    op.create_foreign_key(None, 'Conditions', 'Selectors', ['RightSID'], ['SID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Conditions', type_='foreignkey')
    op.drop_constraint(None, 'Conditions', type_='foreignkey')
    op.drop_constraint(None, 'Actions', type_='foreignkey')
    op.drop_constraint(None, 'Actions', type_='foreignkey')
    # ### end Alembic commands ###
