# Generated by Django 5.1.5 on 2025-02-07 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal", "0002_auto_add_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("max_spending", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "time_period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="internal.user"
                    ),
                ),
            ],
        ),
    ]
