# Generated by Django 5.1.5 on 2025-02-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal", "0002_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
