# Generated by Django 5.1.5 on 2025-02-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal", "0003_user_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
