# Generated by Django 5.1.5 on 2025-02-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal", "0004_user_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="budget",
        ),
        migrations.AddField(
            model_name="user",
            name="budgetName",
            field=models.CharField(default="", max_length=30),
        ),
    ]
