"""Update exp Model4

Revision ID: 140e7baa97d7
Revises: 41c96c77143a
Create Date: 2025-04-15 10:12:00.172364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '140e7baa97d7'
down_revision: Union[str, None] = '41c96c77143a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'grant_expense', 'grant_category', ['category'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grant_expense', type_='foreignkey')
    # ### end Alembic commands ###
