"""Added Other Rules Routes

Revision ID: 24de618a7ad9
Revises: e764707a8cbe
Create Date: 2025-03-23 17:16:30.137563

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "24de618a7ad9"
down_revision: Union[str, None] = "e764707a8cbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
