"""Expense update

Revision ID: 41c96c77143a
Revises: b1dc3ba1b856
Create Date: 2025-04-14 21:00:09.966328

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from app.models import ApprovalStatus
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "41c96c77143a"
down_revision: Union[str, None] = "b1dc3ba1b856"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    approval_status = postgresql.ENUM(ApprovalStatus, name="approvalstatus")
    approval_status.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        "grant_approval",
        "status",
        existing_type=sa.VARCHAR(),
        type_=approval_status,
        existing_nullable=False,
        postgresql_using="status::approvalstatus",
    )
    op.drop_constraint(
        "grant_approval_grant_id_fkey", "grant_approval", type_="foreignkey"
    )
    op.drop_column("grant_approval", "level")
    op.drop_column("grant_approval", "grant_id")
    op.drop_column("grant_expense", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    approval_status = postgresql.ENUM(ApprovalStatus, name="approvalstatus")
    approval_status.drop(op.get_bind())
    op.add_column(
        "grant_expense",
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "grant_approval",
        sa.Column("grant_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "grant_approval",
        sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "grant_approval_grant_id_fkey", "grant_approval", "grant", ["grant_id"], ["id"]
    )
    op.alter_column(
        "grant_approval",
        "status",
        existing_type=sa.Enum("APPROVED", "REJECTED", name="approvalstatus"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
