"""Added Filter Table

Revision ID: 4c203bef5d2a
Revises: e0692df488d1
Create Date: 2025-03-21 13:24:01.704061

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c203bef5d2a"
down_revision: Union[str, None] = "e0692df488d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table(
        "SystemRulesTables",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.bulk_insert(
        table,
        [
            {"name": "Rules"},
            {"name": "Selectors"},
            {"name": "Conditions"},
            {"name": "Actions"},
            {"name": "SystemRulesTables"},
            {"name": "alembic_version"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("SystemRulesTables")
    # ### end Alembic commands ###
