"""rule system tables

Revision ID: 82e2b5d48000
Revises: b24e809c2770
Create Date: 2025-03-17 13:03:13.409402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '82e2b5d48000'
down_revision: Union[str, None] = 'b24e809c2770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('RuleID', sa.Integer(), nullable=False),
    sa.Column('CID', sa.Integer(), nullable=False),
    sa.Column('Conjunction', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Conditions',
    sa.Column('CID', sa.Integer(), nullable=False),
    sa.Column('LeftSID', sa.Integer(), nullable=False),
    sa.Column('Operator', sa.TEXT(), nullable=True),
    sa.Column('RightSID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('CID')
    )
    op.create_table('Rule',
    sa.Column('RuleID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.TEXT(), nullable=True),
    sa.Column('Description', sa.TEXT(), nullable=True),
    sa.Column('Trigger', sa.TEXT(), nullable=True),
    sa.Column('Table', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('RuleID')
    )
    op.create_table('Selectors',
    sa.Column('SID', sa.Integer(), nullable=False),
    sa.Column('Schema', sa.TEXT(), nullable=True),
    sa.Column('Table', sa.TEXT(), nullable=True),
    sa.Column('Target', sa.TEXT(), nullable=True),
    sa.Column('Aggregator', sa.TEXT(), nullable=True),
    sa.Column('Type', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('SID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Selectors')
    op.drop_table('Rule')
    op.drop_table('Conditions')
    op.drop_table('Actions')
    # ### end Alembic commands ###
