"""Update Grant Model

Revision ID: 95fd7e7c1c85
Revises: 7f773ae79e12
Create Date: 2025-04-14 18:09:55.638900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '95fd7e7c1c85'
down_revision: Union[str, None] = '7f773ae79e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_grant_grant_number', table_name='grant')
    op.drop_column('grant', 'grant_number')
    op.add_column('grant_expense', sa.Column('grant_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'grant_expense', 'grant', ['grant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grant_expense', type_='foreignkey')
    op.drop_column('grant_expense', 'grant_id')
    op.add_column('grant', sa.Column('grant_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_grant_grant_number', 'grant', ['grant_number'], unique=True)
    # ### end Alembic commands ###
